# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-03-05 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160305_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Levels'),
        ),
    ]
